experiment_name: "Benchmark_LSTM_Baseline_1"
output_dir: "benchmarkResults/lstm_001"

preprocessing:
  framerate: 60
  confidence_threshold: 0.4
  exclude_ratio: 0.1
  min_segment_length: 60
  outlier_ratio: 0.2

  use_filter: true    # Use Butterworth filter for smoothing

  # Butterworth filter params
  filter_cutoff: 6
  filter_order: 4

event_detector:
  method: "NeuralNet" # "NeuralNet" or "Heuristic"

  neural_net:
    experiment_path: "experiments/LSTM_Baseline_Halpe"
    checkpoint: "best_model.pth"

    post_processing:
      threshold: 0.6
      min_distance_sec: 0.25

  heuristic:
    method: "Zeni"
    skeleton: "HALPE"
    seed: 3
    train_split: 0.8
    params:
      min_peak_distance: 20
      prominence: 10
      motion_threshold: 0.1 # Pixels per frame

data:
  dataset_root: "dataset/PROCESSED"
  annotation_root: "annotations"

  # If true, the whole dataset is used, if false, only the validation part of the seed is used.
  use_full_dataset: False

evaluation:
  tolerance_ms: 150       # Match tolerance
