experiment_name: "Benchmark_Desailly"
output_dir: "benchmarkResults/desailly"

preprocessing:
  framerate: 60
  confidence_threshold: 0.4
  exclude_ratio: 0.1
  min_segment_length: 60
  outlier_ratio: 0.2

  use_filter: true    # Use Butterworth filter for smoothing

  # Butterworth filter params
  filter_cutoff: 6
  filter_order: 4

event_detector:
  method: "Heuristic" # "NeuralNet" or "Heuristic"

  neural_net:
    experiment_path: "experiments/LSTM_Baseline_Halpe"
    checkpoint: "best_model.pth"

    post_processing:
      threshold: 0.6
      min_distance_sec: 0.25

  heuristic:
    method: "Desailly"
    skeleton: "HALPE"
    seed: 3
    train_split: 0.6
    val_split: 0.2
    test_split: 0.2
    params:
      gait_frequency: null
      hs_cutoff_factor: 0.5
      to_cutoff_factor: 1.1
      min_peak_distance: 30
      prominence: null

data:
  dataset_root: "dataset/PROCESSED/rtmlib"
  annotation_root: "annotations"

  # If true, the whole dataset is used, if false, only the validation part of the seed is used.
  use_full_dataset: False

evaluation:
  strict_tolerance_ms: 50
  loose_tolerance_ms: 150
