experiment_name: "Benchmark_Bonci"
output_dir: "benchmarkResults/bonci"

preprocessing:
  framerate: 60
  confidence_threshold: 0.4
  exclude_ratio: 0.1
  min_segment_length: 60
  outlier_ratio: 0.2

  use_filter: true    # Use Butterworth filter for smoothing

  # Butterworth filter params
  filter_cutoff: 6
  filter_order: 4

event_detector:
  method: "Heuristic" # "NeuralNet" or "Heuristic"

  heuristic:
    method: "Bonci"
    skeleton: "HALPE"
    seed: 3
    train_split: 0.6
    val_split: 0.2
    test_split: 0.2
    params:
      hs_velocity_factor: 0.5
      to_velocity_factor: 0.8
      search_window_size: 3

      velocity_filter_cutoff: 6.0
      velocity_filter_order: 4

      zeni_params:
        min_peak_distance: 20
        prominence: 10

data:
  dataset_root: "dataset/PROCESSED/rtmlib"
  annotation_root: "annotations"

  # If true, the whole dataset is used, if false, only the validation part of the seed is used.
  use_full_dataset: False

evaluation:
  strict_tolerance_ms: 50
  loose_tolerance_ms: 150
